query GetFiles($pagination: PaginationInput, $search: String, $filter: FilesFilterInput) {
  getFiles(pagination: $pagination, search: $search, filter: $filter) {
    items {
      id
      originalName
      mimeType
      size
      url
      updatedAt
      isPublic
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}

query GetFolders($pagination: PaginationInput, $search: String, $filter: FolderFilterInput) {
  getFolders(pagination: $pagination, search: $search, filter: $filter) {
    items {
      id
      name
      path
      updatedAt
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}

query GetFileShareLinks($fileId: ID!, $pagination: PaginationInput, $search: String, $filter: ShareLinkFilterInput) {
  getFileShareLinks(fileId: $fileId, pagination: $pagination, search: $search, filter: $filter) {
    items {
      id
      token
      url
      expiresAt
      createdAt
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}

query GetFolderShareLinks($folderId: ID!, $pagination: PaginationInput, $search: String, $filter: ShareLinkFilterInput) {
  getFolderShareLinks(folderId: $folderId, pagination: $pagination, search: $search, filter: $filter) {
    items {
      id
      token
      url
      expiresAt
      createdAt
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}
