query GetFiles($filter: FilesFilterInput, $pagination: PaginationInput) {
  getFiles(filter: $filter, pagination: $pagination) {
    items {
      id
      originalName
      mimeType
      size
      url
      updatedAt
      isPublic
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}

query GetFolders($filter: FolderFilterInput, $pagination: PaginationInput) {
  getFolders(filter: $filter, pagination: $pagination) {
    items {
      id
      name
      path
      updatedAt
    }
    pageInfo {
      totalItems
      totalPages
      currentPage
    }
  }
}

query GetFileShareLinks($fileId: ID!) {
  getFileShareLinks(fileId: $fileId) {
    id
    token
    url
    expiresAt
    createdAt
  }
}

query GetFolderShareLinks($folderId: ID!) {
  getFolderShareLinks(folderId: $folderId) {
    id
    token
    url
    expiresAt
    createdAt
  }
}
